services:
  frontend:
    image: frontend
    build:
      context: frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    command: [ "npm", "start" ]

  backend:
    image: backend
    build:
      context: backend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 4000:4000
      - 9229:9229
    command: [ "npm","run", "debug" ]
